project:
    output-dir: build
    render:
        - "data-report.qmd"

format:
    html:
        title: "Data Report"
        subtitle: "Data Cleaning, Analysis and Preperation"
        author: "DS-22t"
        theme: united
        smooth-scroll: true

        toc: true
        toc-depth: 3
        toc-location: right

        number-sections: true
        number-depth: 5

        code-fold: false
        code-line-numbers: false
        code-copy: true
        code-annotations: true

    pdf:
        title: "Data Report"
        subtitle: "Data Cleaning, Analysis and Preperation"
        author: "DS-22t"
        theme: united
        papersize: A4

        toc: false
        toc-depth: 3

        number-sections: true
        number-depth: 5
