project:
    output-dir: _build

toc: true
toc-depth: 2
toc-expand: true
number-sections: true

execute:
    warning: false
    error: false

format:
    html:
        theme: united

        code-fold: true
        code-copy: true
        highlight-style: github

        standalone: true
        embed-resources: true
        self-contained: true
        self-contained-math: true

    pdf:
        documentclass: scrreprt
        papersize: a4paper

        margin-left: 2cm
        margin-right: 2cm
        margin-top: 2cm
        margin-bottom: 2cm
